In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5])

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1.ndim

1

In [ ]:
arr1.size

5

In [ ]:
arr1.shape

(5,)

In [ ]:
arr1[3]

4

In [ ]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])


In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2.size

8

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr2[0][2]

3

In [ ]:
arr2[1][1]

6

In [ ]:
arr2.ndim

2

In [ ]:
arr3=np.array([[[1,2,3,34,6,67,89,78,90],[4,5,6,0,9,7,65,54,45],[4,5,6,0,9,7,65,54,45]],[[7,8,9,24,45,46,87,45,80],[10,11,12,13,14,15,16,17,87],[4,5,6,0,9,7,65,54,45]]])

In [ ]:
arr3

array([[[ 1,  2,  3, 34,  6, 67, 89, 78, 90],
        [ 4,  5,  6,  0,  9,  7, 65, 54, 45],
        [ 4,  5,  6,  0,  9,  7, 65, 54, 45]],

       [[ 7,  8,  9, 24, 45, 46, 87, 45, 80],
        [10, 11, 12, 13, 14, 15, 16, 17, 87],
        [ 4,  5,  6,  0,  9,  7, 65, 54, 45]]])

In [ ]:
arr3.shape

(2, 3, 9)

In [ ]:
arr3.ndim

3

In [ ]:
arr3[0][1][0]

4

In [ ]:
arr3[0][1][2]

6

In [ ]:
#slicing

In [ ]:
arr3[0][1][0:3]

array([4, 5, 6])

In [ ]:
arr3[1][0][3:6]

array([24, 45, 46])

In [ ]:
arr3[1][2][1:7:2]

array([5, 0, 7])

In [ ]:
arr3[1][2][: : -1]

array([45, 54, 65,  7,  9,  0,  6,  5,  4])

In [ ]:
arr3[1][2][-2:-6:-1]

array([54, 65,  7,  9])

In [ ]:
arr3[0][2][-2:-10:-2]

array([54,  7,  0,  5])