In [ ]:
# Numpy :
#     arrays
#     ndarray
#     slicing
#     indexing
#     ndim
#     shape
#     where ::::::::::::::::
#         CRUD operations

# reshape : this is a method that help us to reshape the shape of data

### 1-D ndarray =-----> 2-D array

In [ ]:
import numpy as np

In [ ]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23])

In [ ]:
arr.ndim

1

In [ ]:
# reshape()

In [ ]:
# np.reshape(objectname, shape)

# objectname.reshaape(shape)

In [ ]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23])

In [ ]:
np.reshape(arr, (3, 3))

array([[12, 34, 45],
       [56, 78, 45],
       [34, 56, 23]])

In [ ]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23])

In [ ]:
np.reshape(arr, (1, 9))

array([[12, 34, 45, 56, 78, 45, 34, 56, 23]])

In [ ]:
qw = np.reshape(arr, (9, 1))

In [ ]:
qw.ndim

2

In [ ]:
qw

array([[12],
       [34],
       [45],
       [56],
       [78],
       [45],
       [34],
       [56],
       [23]])

# 2d to 1D

In [ ]:
zx = np.array([[12, 34, 45, 67, 45, 23], [45, 56, 23, 56, 23, 23]])

In [ ]:
zx

array([[12, 34, 45, 67, 45, 23],
       [45, 56, 23, 56, 23, 23]])

In [ ]:
zx.ndim

2

In [ ]:
zx = np.array([[12, 34, 45, 67, 45, 23], [45, 56, 23, 56, 23, 23]])

In [ ]:
np.reshape(zx, (12))

array([12, 34, 45, 67, 45, 23, 45, 56, 23, 56, 23, 23])

In [ ]:
# -1

In [ ]:
zx = np.array([[12, 34, 45, 67, 45, 23], [45, 56, 23, 56, 23, 23]])

In [ ]:
zx

array([[12, 34, 45, 67, 45, 23],
       [45, 56, 23, 56, 23, 23]])

In [ ]:
np.reshape(zx, -1)

array([12, 34, 45, 67, 45, 23, 45, 56, 23, 56, 23, 23])

In [ ]:
# 1-D to 2-D

In [ ]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23, 34, 657, 45])

In [ ]:
np.reshape(arr, (2, -1))

array([[ 12,  34,  45,  56,  78,  45],
       [ 34,  56,  23,  34, 657,  45]])

In [ ]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23, 34, 657, 45])

In [ ]:
np.reshape(arr, (-1, 6))

array([[ 12,  34,  45,  56,  78,  45],
       [ 34,  56,  23,  34, 657,  45]])

In [ ]:
# 1-D to 3-D

In [ ]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23, 34, 657, 45])

In [ ]:
np.reshape(arr, (2, 2, 3))

array([[[ 12,  34,  45],
        [ 56,  78,  45]],

       [[ 34,  56,  23],
        [ 34, 657,  45]]])

In [ ]:
zx = np.array([[[23, 45, 23], [45, 56, 34]], [[45, 56, 34], [45, 34, 23]]])

In [ ]:
zx

array([[[23, 45, 23],
        [45, 56, 34]],

       [[45, 56, 34],
        [45, 34, 23]]])

In [ ]:
zx.ndim

3

In [ ]:
np.reshape(zx, -1)

array([23, 45, 23, 45, 56, 34, 45, 56, 34, 45, 34, 23])

In [ ]:
# where()

In [ ]:
# sort()

In [ ]:
xyz = np.array([12, 34, 45, 5, 67, 45, 3, 45, 34])

In [ ]:
qw = np.sort(xyz)

In [ ]:
qw

array([ 3,  5, 12, 34, 34, 45, 45, 45, 67])

In [ ]:
qw[: : -1]

array([67, 45, 45, 45, 34, 34, 12,  5,  3])

In [ ]:
# zeros()

In [ ]:
zx = np.zeros((5, 3, 4))

In [ ]:
zx

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
pq = np.ones(3)

In [ ]:
pq

array([1., 1., 1.])

In [ ]:
np.eye

NameError: name 'np' is not defined

In [ ]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.

    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.

        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_func

In [ ]:
x = np.eye(3, 3)

In [ ]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# combining ndarryas

In [ ]:
x = np.array([12, 23, 4, 56])

y = np.array([34, 56, 7, 45])

In [ ]:
x + y

array([ 46,  79,  11, 101])

In [ ]:
x = np.array([12, 23, 4, 56])

y = np.array([34, 56, 7, 45, 45, 34, 2])

In [ ]:
# 1) concatenate
# 2) vstack

In [ ]:
np.concatenate((x, y))

array([12, 23,  4, 56, 34, 56,  7, 45, 45, 34,  2])

In [ ]:
x = np.array([12, 23, 4, 56])
y = np.array([34, 56, 2, 3])

In [ ]:
np.vstack((x, y))

array([[12, 23,  4, 56],
       [34, 56,  2,  3]])

In [ ]:
sort()
contactemate()
vstack()
eye()
zeros()
ones()

In [ ]:
# random