In [2]:
import numpy as np
from numpy import random

In [ ]:
# randint()--->

In [3]:
zx= random.randint(100)

In [4]:
zx

60

In [5]:
zx= random.randint(10,30)
zx

23

In [6]:
# size--->

In [7]:
zx=random.randint(10,50,size=5)
zx


array([45, 10, 15, 11, 47])

In [ ]:
zx=random.randint(11,50,size=(3,5))
zx


array([[36, 28, 46, 33, 49],
       [15, 15, 33, 14, 35],
       [36, 17, 13, 27, 38]])

In [ ]:
px=random.randint(1,5,size=(3,4,3))
px

array([[[3, 3, 1],
        [4, 1, 2],
        [4, 1, 3],
        [2, 2, 1]],

       [[2, 4, 3],
        [4, 1, 2],
        [4, 4, 3],
        [2, 3, 4]],

       [[3, 4, 1],
        [3, 4, 3],
        [2, 1, 4],
        [4, 4, 1]]])

In [ ]:
# randint------> generate elements from sppecific range to specxific range
# randint(start,end,size=(dimentins))

In [ ]:
# rand()-------> 0to1 elements will be generated

In [ ]:
x=random.rand()
x

0.8855461355042433

In [ ]:
# x=random.rand(size=(10))
# this is not executed like randint

In [ ]:
x=random.rand(10)
x

array([0.81337351, 0.96187714, 0.28998169, 0.32504224, 0.30915436,
       0.24286164, 0.90484933, 0.46843943, 0.97355617, 0.40948641])

In [ ]:
x=random.rand(4,5)
x

array([[0.03252974, 0.24860414, 0.69098066, 0.98293605, 0.14734475],
       [0.08225741, 0.96430458, 0.7087963 , 0.49904712, 0.57829027],
       [0.27461896, 0.72837078, 0.16951914, 0.35173769, 0.27680857],
       [0.12812942, 0.82927334, 0.60737875, 0.57977001, 0.68127939]])

In [ ]:
# random

In [ ]:
pq=random.random()
pq

0.26252794688372505

In [ ]:
# choice

In [ ]:
zx=random.choice([1,2,3,4,5,6,7,8,9],size=5)
zx

array([1, 2, 6, 5, 1])

In [ ]:
zx=random.choice([1,2,3,4,5,6,7,8,9],size=(5,6))
zx

array([[7, 5, 6, 1, 4, 8],
       [5, 1, 6, 5, 6, 2],
       [8, 8, 8, 1, 1, 9],
       [8, 5, 7, 4, 1, 2],
       [7, 6, 6, 6, 7, 4]])

In [ ]:
# shuffle

In [ ]:
zx=np.array([1,2,3,4,5,6,7,8,9])


In [ ]:
pq=random.shuffle(zx)


In [ ]:
zx

array([1, 8, 6, 4, 2, 3, 5, 9, 7])

In [ ]:
zx=np.array([1,2,1,2,3,4,1,5,3,3,2,1])
np.unique(zx)

array([1, 2, 3, 4, 5])