In [ ]:
# reshape : this helps to reshape the shape of data

In [ ]:
# 1d->2d

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
arr.ndim

1

In [ ]:
# np.reshape(object name,shape)

In [ ]:
# object_name.reshape(shape)uu

In [ ]:
np.reshape(arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])

In [ ]:
np.reshape(arr,(2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,4,7])

In [ ]:
np.reshape(arr,(5,-1))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [4, 7]])

In [ ]:
np.reshape(arr,(-1,5))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 4, 7]])

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,4])

In [ ]:
# 2d->1d

In [ ]:
az=np.array([[1,2,3],[4,5,6]])

In [ ]:
np.reshape(az,(6))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.reshape(az,-1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 1d->3d

In [ ]:
ap=np.array([1,2,3,4,5,6,7,8,4,33,4,5])

In [ ]:
ap.ndim

1

In [ ]:
len(ap)

12

In [ ]:
np.reshape(ap,(2,2,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  4],
        [33,  4,  5]]])

In [ ]:
# 3d->1d

In [ ]:
xc=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
xc.ndim

3

In [ ]:
np.reshape(xc,-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# where
# sort

In [ ]:
a = np.array([34,5,67,88,8,97,5,4,23,3,32,45,54,22,43,45])

In [ ]:
a

array([34,  5, 67, 88,  8, 97,  5,  4, 23,  3, 32, 45, 54, 22, 43, 45])

In [ ]:
b=np.sort(a)

In [ ]:
b[: : -1]

array([97, 88, 67, 54, 45, 45, 43, 34, 32, 23, 22,  8,  5,  5,  4,  3])

In [ ]:
# zeroes

In [ ]:
s=np.zeros((2,4,5))

In [ ]:
s

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
f=np.ones((5))

In [ ]:
f

array([1., 1., 1., 1., 1.])

In [ ]:
g=np.ones((4,4))

In [ ]:
g

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# other functions

In [ ]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__ar

In [ ]:
x=np.eye(3)


In [ ]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
y=np.eye(3,3,k=2)

In [ ]:
y

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# combining ndarrays

In [ ]:
a=np.array([12,34,56])
b=np.array([78,91,12])

In [ ]:
a+b #addition of elements in an array

array([ 90, 125,  68])

In [ ]:
# comine methods

In [ ]:
# 1. np.concatenate
# 2. vstack

In [ ]:
x = np.array([12, 23, 4, 56])

y = np.array([34, 56, 7, 45, 45, 34, 2])

In [ ]:
np.concatenate((x,y))

array([12, 23,  4, 56, 34, 56,  7, 45, 45, 34,  2])

In [ ]:
b = np.array([12, 23, 4, 56])

c = np.array([34, 56, 7, 45])

In [ ]:
np.vstack((b,c))

array([[12, 23,  4, 56],
       [34, 56,  7, 45]])