In [ ]:
# # numpy
# # Ndarrays
# dimentions
#      1d,2d,3d
# # ndim
# # shape
# indexing
# # slicing

In [ ]:
import numpy as np

In [ ]:
arr= np.array([12,23,4,56,67,89])

In [ ]:
# adding new element in nd array

In [ ]:
# append() -->

In [ ]:
# np.append{object name,element}

In [ ]:
arr

array([12, 23,  4, 56, 67, 89])

In [ ]:
xyz=np.append(arr,100)

In [ ]:
xyz

array([ 12,  23,   4,  56,  67,  89, 100])

In [ ]:
# insert

In [ ]:
# np.insert(objectname,indexnumber,element)

In [ ]:
xyz

array([ 12,  23,   4,  56,  67,  89, 100])

In [ ]:
np.insert(xyz,2,120)

array([ 12,  23, 120,   4,  56,  67,  89, 100])

In [ ]:
np.insert(xyz,3,[23,4,5,78])

array([ 12,  23,   4,  23,   4,   5,  78,  56,  67,  89, 100])

In [ ]:
abc=np.array([1,2,3,4,5,6,7,8])

In [ ]:
index_number=[1,4,6]
elements=[10,20,30]

In [ ]:
np.insert(abc,index_number,elements)

array([ 1, 10,  2,  3,  4, 20,  5,  6, 30,  7,  8])

In [ ]:
arr3=np.array([1,2,3,4,5,6])

In [ ]:
np.insert(abc,[1,4,6],[10,20,30])

array([ 1, 10,  2,  3,  4, 20,  5,  6, 30,  7,  8])

In [ ]:
# replacing elements in array/update elements

In [ ]:
arr3=np.array([1,2,3,4,5,6,7,8])

In [ ]:
# ObjectName[indexnumber]=new_element

In [ ]:
arr3[2]=100

In [ ]:
arr3

array([  1,   2, 100,   4,   5,   6])

In [ ]:
arr3=np.array([1,2,3,4,5,6,7,8])

In [ ]:
arr3[[1,4,-1]]=[13,14,15]

In [ ]:
arr3

array([ 1, 13,  3,  4, 14,  6,  7, 15])

In [ ]:
# delete elements in np array

In [ ]:
np.delete(arr3,2)

array([ 1, 13,  4, 14,  6,  7, 15])

In [ ]:
np.delete(arr3,-1)

array([ 1, 13,  3,  4, 14,  6,  7])

In [ ]:
np.delete(arr3,[1,2,-2])

array([ 1,  4, 14,  6, 15])

In [ ]:
# append
# insert
# replace element
# delete

In [ ]:
xyz=np.array([1,2,3,4,5,6])


In [ ]:
np.insert(xyz,[0],[10,11,12,13,14])

array([10, 11, 12, 13, 14,  1,  2,  3,  4,  5,  6])

In [ ]:
# own work
# 2 x 2 = 2, 2 x 3 = 4 ,2 x 3 = 6

In [ ]:
zx=np.array([])

In [ ]:
zx=[]
for i in range(1,11):
  zx.append(f"2 x {i} = {2*i}")


In [ ]:
zx

['2 x 1 = 2',
 '2 x 2 = 4',
 '2 x 3 = 6',
 '2 x 4 = 8',
 '2 x 5 = 10',
 '2 x 6 = 12',
 '2 x 7 = 14',
 '2 x 8 = 16',
 '2 x 9 = 18',
 '2 x 10 = 20']

In [ ]:
zx = np.array([])

In [ ]:
for i in range(1,11):
  zx=np.append(zx,f"2 x {i} = {2*i}")

In [ ]:
zx

array(['2 x 1 = 2', '2 x 2 = 4', '2 x 3 = 6', '2 x 4 = 8', '2 x 5 = 10',
       '2 x 6 = 12', '2 x 7 = 14', '2 x 8 = 16', '2 x 9 = 18',
       '2 x 10 = 20'], dtype='<U32')

In [ ]:
# where()  ----> help to get index number of the data


In [ ]:
arr = np.array([12, 23, 34, 45, 56, 67, 45, 34, 23, 34, 23])


In [ ]:
# np.where(object with condation)


In [ ]:
# np.where(arr)


In [ ]:
# ==
# !=
# >
# <
# <=
# >=

In [ ]:
np.where(arr==67)

(array([5]),)

In [ ]:
np.where(arr==45)

(array([3, 6]),)

In [ ]:
np.where(arr>=47)

(array([4, 5]),)

In [ ]:
np.where(arr<=46)

(array([ 0,  1,  2,  3,  6,  7,  8,  9, 10]),)

In [ ]:
# range() -----> python


In [ ]:
# arange()


In [ ]:
# np.arange(start, end, increment)


In [ ]:
arr3=np.arange(1,21)

In [ ]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr4=np.arange(1,21,2)

In [ ]:
arr4

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])