In [1]:
import numpy as np


In [ ]:
# ques1  
# Define a NumPy array with the numbers 0 through 9 and reshape it into a 3x3 array. Calculate the cumulative sum along each row.

In [3]:
ax=np.arange(9)

In [4]:
ax

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
sd=ax.reshape(3,3)

In [6]:
sd

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
df=np.cumsum(sd,axis=1)

In [8]:
df

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [9]:
# qyes 2
# Generate a 4x4 NumPy array with random integers between 1 and 100. Replace all even numbers with 0 and odd numbers with 1.

In [53]:
ad=np.random.randint(0,100,(4,4))

In [18]:
ad

array([[14, 20, 16, 28],
       [48, 58, 21, 84],
       [32,  9,  5, 90],
       [23, 57, 80, 40]])

In [19]:
np.where(ad%2==0,0,1)

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 0],
       [1, 1, 0, 0]])

In [20]:
# ques 3
# Create a NumPy array with the elements ["apple", "banana", "cherry"] and then find the index of the element "banana".

In [21]:
arr=np.array(["apple", "banana", "cherry"])

In [22]:
arr

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [29]:
np.where(arr=="banana")

(array([1]),)

In [ ]:
# only practice

In [30]:
ax=np.array([2,3,4,5,5,6,7,7,8,0,5,3])

In [31]:
ax

array([2, 3, 4, 5, 5, 6, 7, 7, 8, 0, 5, 3])

In [33]:
np.where(ax==5)

(array([ 3,  4, 10]),)

In [34]:
# ques 4
# Define a NumPy array containing the numbers 1 through 20 and reshape it into a 4x5 array. Compute the mean of each row

In [35]:
sd=np.arange(20)

In [36]:
sd

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
we=sd.reshape(4,5)

In [39]:
we

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
fg=np.mean(we,axis=1)

In [46]:
fg

array([ 2.,  7., 12., 17.])

In [47]:
# ques5
# Generate a 5x5 NumPy array with random integers between 1 and 10. Replace all values above 5 with 0 and all values below 5 with 1.

In [54]:
df=np.random.randint(1,10,(5,5))

In [55]:
df

array([[5, 9, 4, 9, 4],
       [5, 1, 8, 3, 2],
       [5, 1, 3, 8, 2],
       [2, 6, 5, 4, 3],
       [9, 6, 2, 5, 1]])

In [57]:
np.where(df>=5,0,1)

array([[0, 0, 1, 0, 1],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [0, 0, 1, 0, 1]])

In [58]:
# ques6
# Create a NumPy array with the elements ["red", "green", "blue"] and then count the occurrences of each unique element.

In [67]:
kl=np.array(["blue","red", "green", "blue","red","blue","green","blue","red","green"])

In [68]:
kl

array(['blue', 'red', 'green', 'blue', 'red', 'blue', 'green', 'blue',
       'red', 'green'], dtype='<U5')

In [69]:
np.unique(kl,return_counts=True)

(array(['blue', 'green', 'red'], dtype='<U5'), array([4, 3, 3]))

In [ ]:
# another way

In [70]:
j=np.array(['r','e','d','g','r','e','e','n','b','l','u','e'])

In [71]:
j

array(['r', 'e', 'd', 'g', 'r', 'e', 'e', 'n', 'b', 'l', 'u', 'e'],
      dtype='<U1')

In [72]:
np.unique(j,return_counts=True)

(array(['b', 'd', 'e', 'g', 'l', 'n', 'r', 'u'], dtype='<U1'),
 array([1, 1, 4, 1, 1, 1, 2, 1]))

In [74]:
# ques 7
# Define a NumPy array containing the numbers 1 through 16 and reshape it into a 4x4 array. Extract the diagonal elements and compute their product.

In [77]:
s=np.arange(1,17)

In [78]:
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [82]:
u=np.reshape(s,(4,4))

In [83]:
u

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
t=np.diag(u)

In [95]:
t

array([ 1,  6, 11, 16])

In [99]:
# ques 8
# Generate a 3x3 NumPy array with random floating-point numbers between -1 and 1. Compute the absolute value of each element.

In [111]:
ax=np.random.uniform(-1,1,(3,3))

In [112]:
ax

array([[-0.40679214,  0.8824197 , -0.60139403],
       [ 0.98960837, -0.34764411, -0.34877301],
       [-0.80618785,  0.0586424 , -0.88429619]])

In [117]:
np.absolute(ax)

array([[0.40679214, 0.8824197 , 0.60139403],
       [0.98960837, 0.34764411, 0.34877301],
       [0.80618785, 0.0586424 , 0.88429619]])

In [133]:
# ques 9
# Create a NumPy array with the elements ["apple", "banana", "cherry"] and then sort them alphabetically in descending order.

In [134]:
sd=np.array(["apple", "banana", "grapes","dates","pineapple","cherry"])

In [140]:
sd[::-1].sort()

In [141]:
sd

array(['pineapple', 'grapes', 'dates', 'cherry', 'banana', 'apple'],
      dtype='<U9')

In [142]:
sd[::-1]

array(['apple', 'banana', 'cherry', 'dates', 'grapes', 'pineapple'],
      dtype='<U9')

In [143]:
# ques 10
# Define a NumPy array containing the numbers 1 through 25 and reshape it into a 5x5 array. Compute the sum of the diagonal elements.

In [150]:
sf=np.arange(1,26)

In [151]:
sf

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [152]:
a=np.reshape(sf,(5,5))

In [154]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [155]:
sum(np.diag(a))

65

In [156]:
# ques 11
# Generate a 6x6 NumPy array with random integers between 0 and 100. Find the maximum value in each row and replace it with the string "MAX".

In [167]:
s=np.random.randint(0,100,(6,6))

In [239]:
s

array([[89, 82, 35,  4, 95, 97],
       [57, 25, 55, 39, 55, 75],
       [77, 68, 19, 70, 84, 66],
       [38, 76, 53, 11, 58,  0],
       [68, 14, 77, 53, 79, 98],
       [ 6, 11, 39, 35, 65, 10]])

In [272]:
e=np.max(s,axis=1)
e

array([97, 75, 84, 76, 98, 65])

In [273]:
em=np.array([])

In [274]:
oneD=s.reshape(-1)
for i in e:
    ind=np.where(oneD==i)
    em=np.append(em,ind)

em=np.int_(em)
em

array([ 5, 11, 16, 19, 29, 34])

In [275]:
t=np.where((s==np.max(s,axis=1)),'MAX',s)

In [276]:
t

array([['89', '82', '35', '4', '95', '97'],
       ['57', '25', '55', '39', '55', '75'],
       ['77', '68', '19', '70', '84', '66'],
       ['38', '76', '53', '11', '58', '0'],
       ['68', '14', '77', '53', '79', '98'],
       ['6', '11', '39', '35', '65', '10']], dtype='<U21')

In [277]:
new=t.reshape(-1)
new

array(['89', '82', '35', '4', '95', '97', '57', '25', '55', '39', '55',
       '75', '77', '68', '19', '70', '84', '66', '38', '76', '53', '11',
       '58', '0', '68', '14', '77', '53', '79', '98', '6', '11', '39',
       '35', '65', '10'], dtype='<U21')

In [278]:
new[[em]]='MAX'

In [279]:
new.reshape(6,6)

array([['89', '82', '35', '4', '95', 'MAX'],
       ['57', '25', '55', '39', '55', 'MAX'],
       ['77', '68', '19', '70', 'MAX', '66'],
       ['38', 'MAX', '53', '11', '58', '0'],
       ['68', '14', '77', '53', '79', 'MAX'],
       ['6', '11', '39', '35', 'MAX', '10']], dtype='<U21')

In [2]:
# ques 11 another way
# Generate a 6x6 NumPy array with random integers between 0 and 100. Find the maximum value in each row and replace it with the string "MAX".

In [319]:
q=np.random.randint(0,100,(6,6))
q

array([[68, 19, 69, 33, 55, 92],
       [33, 58, 49, 68, 70, 58],
       [55, 10, 15, 76, 52, 40],
       [72, 18, 67, 51, 51,  5],
       [47,  2, 13,  9, 37, 54],
       [ 0, 79, 21,  5, 41, 86]])

In [320]:
r=np.max(q,axis=1)
r

array([92, 70, 76, 72, 54, 86])

In [328]:
s=[]
for i in range(6):
    s.append(np.where((q[i]==r[i]),'MAX',q[i]))
    t=np.concatenate(s) 
    # t=np.vstack(s) 
u=np.reshape(t,(6,6))
print("Original array\n",q,"\n\nconverted array\n",u)
# print("Original array\n",q,"\n\nconverted array\n",t)

    

Original array
 [[68 19 69 33 55 92]
 [33 58 49 68 70 58]
 [55 10 15 76 52 40]
 [72 18 67 51 51  5]
 [47  2 13  9 37 54]
 [ 0 79 21  5 41 86]] 

converted array
 [['68' '19' '69' '33' '55' 'MAX']
 ['33' '58' '49' '68' 'MAX' '58']
 ['55' '10' '15' 'MAX' '52' '40']
 ['MAX' '18' '67' '51' '51' '5']
 ['47' '2' '13' '9' '37' 'MAX']
 ['0' '79' '21' '5' '41' 'MAX']]


In [266]:
# ques 12
# Create a NumPy array with the elements ["cat", "dog", "bird", "cat", "dog", "fish"] and then count the occurrences of each unique element.

In [268]:
r=np.array(["cat", "dog", "bird", "cat", "dog", "fish"])
r

array(['cat', 'dog', 'bird', 'cat', 'dog', 'fish'], dtype='<U4')

In [271]:
t=np.unique(r,return_counts=True)
t

(array(['bird', 'cat', 'dog', 'fish'], dtype='<U4'), array([1, 2, 2, 1]))

In [272]:
# ques 13
# Define a NumPy array containing the numbers 1 through 12 and reshape it into a 3x4 array. Calculate the standard deviation of each column.

In [289]:
s=np.arange(1,13)
t=np.reshape(s,(3,4))
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [292]:
np.std(t,axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [293]:
# ques 14
# Generate a 4x4 NumPy array with random integers between -50 and 50. Replace all negative values with 0 and all positive values with 1.

In [303]:
e=np.random.randint(-50,50,(4,4))
e

array([[-43, -29, -49,  33],
       [ 24, -32,  44,  36],
       [-49,  48,  26,  44],
       [-48,  12, -46,  42]])

In [304]:
s=np.where(e<0,0,1)
s

array([[0, 0, 0, 1],
       [1, 0, 1, 1],
       [0, 1, 1, 1],
       [0, 1, 0, 1]])

In [305]:
# ques 15
# Create a NumPy array with the elements ["apple", "banana", "cherry", "apple", "banana"]. Remove duplicates from the array.

In [331]:
d=np.array(["apple", "banana", "cherry", "apple", "banana"])
r=np.unique(d)
r

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [332]:
# ques 16
# Define a NumPy array containing the numbers 1 through 16 and reshape it into a 4x4 array. Extract the elements in the last column.

In [334]:
g=np.arange(1,17)
g

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [336]:
t=np.reshape(g,(4,4))
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [361]:
# help(np.extract)
# np.extract(t%4==0,t)
t[: ,-1]

array([ 4,  8, 12, 16])

In [362]:
# ques 17
# Generate a 5x5 NumPy array with random floating-point numbers between 0 and 1. Round each element to the nearest integer.

In [372]:
e=np.random.rand(5,5)
e

array([[0.98500831, 0.53418788, 0.10191145, 0.54495089, 0.28686865],
       [0.58546934, 0.57306306, 0.01487529, 0.41331528, 0.20409672],
       [0.05891259, 0.92599861, 0.43507031, 0.85221569, 0.08301429],
       [0.38369296, 0.63147026, 0.88789966, 0.31313108, 0.56620481],
       [0.23191601, 0.13675623, 0.84441338, 0.7092526 , 0.54830119]])

In [373]:
np.round(e)

array([[1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 1.],
       [0., 0., 1., 1., 1.]])

In [375]:
# ques 18
# Create a NumPy array with the elements ["red", "green", "blue", "red", "green", "blue"]. Replace "red" with "orange".

In [401]:
x=np.array(["red", "green", "blue", "red", "green", "blue"])
x

array(['red', 'green', 'blue', 'red', 'green', 'blue'], dtype='<U5')

In [402]:
t=x[x=="red"]="orange"
x

array(['orang', 'green', 'blue', 'orang', 'green', 'blue'], dtype='<U5')

In [409]:
np.where([x=="blue"])

(array([0, 0]), array([2, 5]))

In [410]:
# ques 19
# Define a NumPy array containing the numbers 1 through 20 and reshape it into a 5x4 array. Compute the sum of each column.

In [412]:
r=np.arange(1,21)
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [415]:
y=np.reshape(r,(5,4))
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [425]:
w=y.sum(axis=0)
w

array([45, 50, 55, 60])

In [426]:
# ques 20
# Generate a 3x3 NumPy array with random integers between 1 and 100. Find the index of the maximum value in the array.

In [449]:
p=np.random.randint(1,100,(3,3))
p

array([[27, 87, 75],
       [10, 41, 37],
       [97, 69, 51]])

In [450]:
c=np.max(p)
c

97

In [451]:
np.where(p==c)

(array([2]), array([0]))

In [528]:
# ques 21 
# genrate 100 elements in 2d ndarray
# 10 rows 5 columns..
# then in that ndarray the elements which are divisible by 2 put 0 instead of element and the elements which is not divisible by 2 put 1 instead of that element or if their is any element which is divisible by 2 and 3 both, put 2 instead of element.

In [529]:
d=np.random.randint(0,100,(10,5))
d

array([[11, 82, 91, 94, 11],
       [ 3, 37,  9, 36, 13],
       [20,  0, 52, 77, 47],
       [13, 58,  3, 54, 56],
       [26, 70, 81, 40, 35],
       [35, 50, 19, 95, 72],
       [77, 39, 15, 92, 61],
       [24,  8, 60, 44, 89],
       [11, 43, 50, 72, 94],
       [39, 27,  4, 22,  8]])

In [531]:
n=d.copy()
n[(d%2==0) & (d%3==0)]=2
n[(d%2==0) & (d%3!=0)]=0
n[(d%2!=0)]=1
n

array([[1, 0, 1, 0, 1],
       [1, 1, 1, 2, 1],
       [0, 2, 0, 1, 1],
       [1, 0, 1, 2, 0],
       [0, 0, 1, 0, 1],
       [1, 0, 1, 1, 2],
       [1, 1, 1, 0, 1],
       [2, 0, 2, 0, 1],
       [1, 1, 0, 2, 0],
       [1, 1, 0, 0, 0]])